DELETE FROM dishes_tab;
DELETE FROM ingredient_tab;

INSERT INTO ingredient_tab (id, name, classification, classification_reason, source_hospital, source_document)
OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Agar-agar', 'can', 'Only clear agar with no fruit pieces; avoid red, purple, blue or dark colours.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (2, 'Apple', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (3, 'Apple juice', 'can', 'OK only if clear, pulp-free and strained.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (4, 'Banana', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (5, 'Barley', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (6, 'Barley water', 'can', 'Only if fully strained with no grain left; for clear liquids use diluted, non-cloudy.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (7, 'Bean sprouts', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (8, 'Bee hoon', 'can', 'Refined noodles are low in fibre if plain (not wholegrain).', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (9, 'Berries', 'cannot', 'Seeds and fibre leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (10, 'Bitter gourd', 'cannot', 'Vegetable fibre and seeds leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (11, 'Black coffee', 'can', 'Plain coffee is fine; can continue into clear liquids without milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (12, 'Blue drinks', 'cannot', 'Dark colours can stain the bowel and look like blood during the scope.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (13, 'Bran cereal', 'cannot', 'Very high in fibre, which leaves a lot of residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (14, 'Broccoli', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (15, 'Brown rice', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (16, 'Brown rice porridge', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (17, 'Buckwheat noodles', 'cannot', 'High-fibre / buckwheat noodles leave more residue — avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (18, 'Cabbage', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (19, 'Carrot', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (20, 'Cauliflower', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (21, 'Chapati', 'cannot', 'Usually higher-fibre flour, which leaves more residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (22, 'Cheese', 'can', 'Fine in the low-residue phase if plain with no nuts, seeds, fruit or vegetables.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (23, 'Chia seeds', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (24, 'Chicken', 'can', 'Low-fibre protein if soft, cut small and well-cooked; avoid tough cuts.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (25, 'Chickpeas', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (26, 'Chilli', 'cannot', 'Seeds and vegetable solids leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (27, 'Chye sim', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (28, 'Clear chicken broth', 'can', 'Fine if fully strained with no solids.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (29, 'Clear fish broth', 'can', 'Fine if fully strained with no solids.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (30, 'Clear jelly', 'can', 'Only clear jelly with no fruit pieces; avoid red, purple, blue or dark colours.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (31, 'Clear soup', 'can', 'Fine if fully strained with no solids left.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (32, 'Clear strained fruit juice', 'can', 'OK only if clear, pulp-free and strained.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (33, 'Coconut milk', 'can', 'Acceptable in the low-residue phase.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (34, 'Colourless soft drink', 'can', 'Clear fluid that leaves little residue; follow fasting timing.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (35, 'Condensed milk', 'can', 'Fine in the low-residue phase if plain; stop once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (36, 'Coriander', 'cannot', 'Garnish pieces add fibre — remove them.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (37, 'Corn', 'cannot', 'Kernels and fibre leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (38, 'Cream', 'can', 'Fine in the low-residue phase if plain; stop once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (39, 'Cucumber', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (40, 'Curry paste', 'cannot', 'Usually contains chilli and vegetable solids that leave residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (41, 'Dark drinks', 'cannot', 'Dark colours can stain the bowel and look like blood during the scope.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (42, 'Dark soy sauce', 'can', 'Fine if smooth with no significant visible vegetable pieces.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (43, 'Dried fruit', 'cannot', 'Concentrated fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (44, 'Egg', 'can', 'Low-fibre protein that leaves little residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (45, 'Eggplant', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (46, 'Evaporated milk', 'can', 'Fine in the low-residue phase if plain; stop once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (47, 'Fish', 'can', 'Low-fibre protein if soft and well-cooked.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (48, 'Fishball', 'can', 'OK only if there are no seeds or vegetable pieces mixed in.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (49, 'Fishcake', 'can', 'OK only if there are no seeds or vegetable pieces mixed in.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (50, 'Flax seeds', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (51, 'French beans', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (52, 'Fresh milk', 'can', 'Fine in the low-residue phase; stop once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (53, 'Fried dishes', 'cannot', 'Oily or fried food is harder on prep quality — choose plain, lightly prepared food.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (54, 'Fried shallots', 'cannot', 'Crunchy garnish adds fibre — remove them.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (55, 'Fruit jelly', 'cannot', 'Fruit pieces leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (56, 'Garlic', 'cannot', 'Vegetable pieces leave residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (57, 'Ginger', 'cannot', 'Vegetable pieces leave residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (58, 'Glucose drink', 'can', 'Clear fluid that leaves little residue; follow fasting timing.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (59, 'Grape juice', 'cannot', 'Dark colour can stain the bowel and look like blood during the scope.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (60, 'Grapes', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (61, 'Guava', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (62, 'High-fibre noodles', 'cannot', 'High-fibre noodles leave more residue in the bowel — avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (63, 'Honey water', 'can', 'Clear fluid that leaves little residue if fully dissolved.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (64, 'Honeydew', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (65, 'Horlicks', 'can', 'OK in the low-residue phase; stop once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (66, 'Isotonic drink (light-coloured)', 'can', 'Light clear fluid is fine; prefer versions without strong added colour.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (67, 'Isotonic drink (red/purple/blue)', 'cannot', 'Dark colours can stain the bowel and look like blood during the scope.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (68, 'Jelly', 'can', 'Only clear jelly with no fruit pieces; avoid red, purple, blue or dark colours.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (69, 'Jelly with fruit pieces', 'cannot', 'Fruit pieces leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (70, 'Kai lan', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (71, 'Kang kong', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (72, 'Kaya', 'can', 'Acceptable in the low-residue phase as a smooth spread.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (73, 'Kopi', 'can', 'OK in the low-residue phase; stop for clear liquids because it contains milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (74, 'Kopi-C', 'can', 'OK in the low-residue phase; stop for clear liquids because it contains milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (75, 'Kopi-O', 'can', 'Plain coffee/tea is fine; can continue into clear liquids without milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (76, 'Kway teow', 'can', 'Refined noodles are low in fibre if plain (not wholegrain).', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (77, 'Laksa leaves', 'cannot', 'Herb leaves add fibre and residue — avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (78, 'Laksa paste', 'cannot', 'Usually contains chilli, herbs and solids that leave residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (79, 'Lemongrass', 'can', 'OK only in tiny amounts for flavour if not eaten as visible pieces.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (80, 'Lentils', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (81, 'Lettuce', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (82, 'Luncheon meat', 'can', 'OK only if there are no seeds or vegetable pieces mixed in.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (83, 'Mango', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (84, 'Mayonnaise', 'can', 'Fine if smooth with no significant visible vegetable pieces.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (85, 'Mee kia', 'can', 'Refined noodles are low in fibre; avoid wholegrain, high-fibre or buckwheat versions.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (86, 'Mee pok', 'can', 'Refined noodles are low in fibre; avoid wholegrain, high-fibre or buckwheat versions.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (87, 'Mee sua', 'can', 'Refined noodles are low in fibre if plain (not wholegrain).', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (88, 'Milo', 'can', 'OK in the low-residue phase; stop once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (89, 'Mixed nuts', 'cannot', 'Nut pieces leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (90, 'Muesli', 'cannot', 'High in fibre from grains, fruit and seeds, which leave residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (91, 'Mung beans', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (92, 'Mushrooms', 'cannot', 'Very high in fibre and leave a lot of residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (93, 'Oats', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (94, 'Oily dishes', 'cannot', 'Oily or fried food is harder on prep quality — choose plain, lightly prepared food.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (95, 'Okra', 'cannot', 'Vegetable fibre and seeds leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (96, 'Onion', 'cannot', 'Vegetable pieces leave residue.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (97, 'Orange', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (98, 'Orange juice', 'can', 'Only if fully clear and strained; pulpy versions leave residue — usually avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (99, 'Oyster sauce', 'can', 'Fine if smooth with no significant visible vegetable pieces.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (100, 'Papaya', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (101, 'Pasta', 'can', 'Refined pasta is low in fibre; avoid wholegrain or high-fibre pasta.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (102, 'Peanuts', 'cannot', 'High in fibre; nut pieces leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (103, 'Pear', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (104, 'Pear juice', 'can', 'OK only if clear, pulp-free and strained.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (105, 'Peas', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (106, 'Pineapple', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (107, 'Plain tea', 'can', 'Plain tea is fine; can continue into clear liquids without milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (108, 'Popcorn', 'cannot', 'Hulls and fibre leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (109, 'Potato', 'can', 'Low-fibre starch if peeled; do not eat the skin.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (110, 'Prawns', 'can', 'Low-fibre protein if soft and well-cooked.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (111, 'Prune juice', 'cannot', 'Contains fibre and is dark — avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (112, 'Prunes', 'cannot', 'High in fibre and leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (113, 'Pulpy fruit juice', 'cannot', 'Pulp and bits leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (114, 'Pumpkin', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (115, 'Pumpkin seeds', 'cannot', 'Seed pieces leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (116, 'Purple drinks', 'cannot', 'Dark colours can stain the bowel and look like blood during the scope.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (117, 'Raisins', 'cannot', 'Concentrated fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (118, 'Red beans', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (119, 'Red drinks', 'cannot', 'Dark colours can stain the bowel and look like blood during the scope.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (120, 'Sambal', 'cannot', 'Often contains chilli seeds or solids that leave residue — preferably avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (121, 'Sausage', 'can', 'OK only if there are no seeds or vegetable pieces mixed in.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (122, 'Seaweed', 'cannot', 'Fibrous and leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (123, 'Sesame seeds', 'cannot', 'Tiny seeds leave residue and are hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (124, 'Shellfish', 'can', 'Low-fibre protein if soft and well-cooked.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (125, 'Sinewy meat cuts', 'cannot', 'Tough connective tissue is harder to digest and clear — choose soft, well-cooked cuts.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (126, 'Smooth almond butter', 'can', 'OK only as a thin smooth layer with no nut chunks.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (127, 'Smooth nut butter', 'can', 'OK only as a thin smooth layer with no nut chunks.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (128, 'Smooth peanut butter', 'can', 'OK only as a thin smooth layer with no nut chunks.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (129, 'Soba', 'cannot', 'High-fibre / buckwheat noodles leave more residue — avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (130, 'Soy bean drink', 'can', 'Fine in the low-residue phase; not suitable once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (131, 'Soy milk', 'can', 'Fine in the low-residue phase; not suitable once clear liquids start.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (132, 'Soy sauce', 'can', 'Fine if smooth with no significant visible vegetable pieces.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (133, 'Soybeans', 'cannot', 'High in fibre and leave residue that is hard to clear.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (134, 'Spinach', 'cannot', 'Vegetable fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (135, 'Spring onion', 'cannot', 'Garnish pieces add fibre — remove them.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (136, 'Squid', 'can', 'Low-fibre protein if soft and well-cooked; avoid tough pieces.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (137, 'Stuffed tofu', 'cannot', 'Vegetable stuffing adds fibre and residue — choose plain tofu instead.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (138, 'Sunflower seeds', 'cannot', 'Seed pieces leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (139, 'Sweet chilli sauce', 'cannot', 'Often contains seeds or vegetable pieces that leave residue — preferably avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (140, 'Sweet potato', 'can', 'Only if peeled and well-cooked; some clinics are stricter.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (141, 'Tau pok', 'can', 'Soft soy protein is low-residue if plain and not stuffed with vegetables.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (142, 'Taukwa', 'can', 'Soft soy protein is low-residue if plain and not stuffed with vegetables.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (143, 'Teh', 'can', 'OK in the low-residue phase; stop for clear liquids because it contains milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (144, 'Teh tarik', 'can', 'OK in the low-residue phase; stop for clear liquids because it contains milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (145, 'Teh-C', 'can', 'OK in the low-residue phase; stop for clear liquids because it contains milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (146, 'Teh-O', 'can', 'Plain tea is fine; can continue into clear liquids without milk.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (147, 'Tofu', 'can', 'Soft soy protein is low-residue if plain and not stuffed with vegetables.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (148, 'Tomato', 'cannot', 'Vegetable fibre and seeds leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (149, 'Tomato juice', 'cannot', 'Pulpy and coloured; can leave residue or stain the view — avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (150, 'Tomato ketchup', 'can', 'Fine if smooth with no significant visible vegetable pieces.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (151, 'Tough meat cuts', 'cannot', 'Tough connective tissue is harder to digest and clear — choose soft, well-cooked cuts.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (152, 'Unstrained fruit juice', 'cannot', 'Pulp and bits leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (153, 'Water', 'can', 'Clear fluid that leaves no residue; follow fasting stop time.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (154, 'Watermelon', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (155, 'White bread', 'can', 'Low in fibre if plain refined white bread.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (156, 'White porridge', 'can', 'Low in fibre, so it leaves little residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (157, 'White rice', 'can', 'Low in fibre, so it leaves little residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (158, 'Whole nuts', 'cannot', 'Nut pieces are high in fibre and leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (159, 'Wholegrain biscuits', 'cannot', 'High-fibre biscuits leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (160, 'Wholegrain bread', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (161, 'Wholegrain noodles', 'cannot', 'Wholegrain noodles are higher in fibre and leave more residue — avoid.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (162, 'Wholemeal biscuits', 'cannot', 'High-fibre biscuits leave residue in the bowel.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (163, 'Wholemeal bread', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (164, 'Yam / taro', 'can', 'Only if peeled and well-cooked; some clinics are stricter.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (165, 'Yellow noodles', 'can', 'Refined noodles are low in fibre; avoid wholegrain, high-fibre or buckwheat versions.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (166, 'Yoghurt', 'can', 'Fine in the low-residue phase if plain with no nuts, seeds, fruit or vegetables.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (167, 'Yong tau foo', 'cannot', 'Vegetable stuffing adds fibre and residue — choose plain tofu instead.', 'DIETICIAN', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (168, 'Apple', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (169, 'Apple juice', 'can', 'Light-coloured apple juice is allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (170, 'Banana', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (171, 'Bean sprouts', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (172, 'Bee hoon', 'can', 'Noodles are allowed if plain and not wholegrain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (173, 'Beef', 'cannot', 'Red meat is avoided on this hospital’s list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (174, 'Berries', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (175, 'Bitter gourd', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (176, 'Black coffee', 'cannot', 'Dark coffee/tea is avoided because it can affect the bowel view.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (177, 'Broccoli', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (178, 'Brown rice', 'cannot', 'High in fibre, which leaves residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (179, 'Brown rice porridge', 'cannot', 'High in fibre, which leaves residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (180, 'Cabbage', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (181, 'Carrot', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (182, 'Cauliflower', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (183, 'Chapati', 'cannot', 'Higher-fibre flatbread that leaves more residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (184, 'Cheese', 'cannot', 'Cheese is avoided on this hospital’s low-residue list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (185, 'Chia seeds', 'cannot', 'Seeds leave residue that is hard to clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (186, 'Chicken', 'can', 'Lean chicken is allowed and leaves little residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (187, 'Chickpeas', 'cannot', 'Beans are high in fibre and leave residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (188, 'Chilli', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (189, 'Chye sim', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (190, 'Clear chicken broth', 'can', 'Clear soup is allowed if it stays clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (191, 'Clear fish broth', 'can', 'Clear soup is allowed if it stays clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (192, 'Clear soup', 'can', 'Clear soup is allowed if it stays clear (not cream soup).', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (193, 'Colourless soft drink', 'can', 'Colourless soft drinks are allowed (e.g. Sprite/7-Up/cream soda).', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (194, 'Coriander', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (195, 'Corn', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (196, 'Cream soda', 'can', 'Colourless soft drink example on the allowed fluids list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (197, 'Cream soup', 'cannot', 'Cream soup is not a clear soup and is listed to avoid.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (198, 'Cucumber', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (199, 'Curry paste', 'cannot', 'Contains vegetable solids; all vegetables are avoided.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (200, 'Dried fruit', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (201, 'Egg', 'can', 'Eggs are allowed and leave little residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (202, 'Eggplant', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (203, 'Fish', 'can', 'Fish is allowed and leaves little residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (204, 'Flax seeds', 'cannot', 'Seeds leave residue that is hard to clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (205, 'French beans', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (206, 'Fresh milk', 'cannot', 'Milk is avoided because it is not part of the allowed fluid list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (207, 'Fried shallots', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (208, 'Garlic', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (209, 'Ginger', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (210, 'Grape juice', 'cannot', 'Dark-coloured liquids can stain the bowel view — avoid.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (211, 'Grapes', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (212, 'Guava', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (213, 'Honeydew', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (214, 'Horlicks', 'cannot', 'Malted drinks are avoided on this hospital’s fluid list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (215, 'Iddiyappam', 'can', 'Rice noodle cake listed as an allowed rice alternative.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (216, 'Iddiyappam / putu mayam', 'can', 'Rice noodle cake listed as an allowed rice alternative.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (217, 'Idli', 'can', 'Soft rice cake listed as an allowed rice alternative.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (218, 'Isotonic drink (red/purple/blue)', 'cannot', 'Red/dark-coloured liquids can stain the bowel view — avoid.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (219, 'Kai lan', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (220, 'Kang kong', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (221, 'Kopi', 'cannot', 'Coffee/tea is avoided; milk drinks are also not allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (222, 'Kopi-C', 'cannot', 'Coffee/tea is avoided; milk drinks are also not allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (223, 'Kopi-O', 'cannot', 'Dark coffee/tea is avoided because it can affect the bowel view.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (224, 'Kway teow', 'can', 'Noodles are allowed if plain and not wholegrain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (225, 'Laksa leaves', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (226, 'Laksa paste', 'cannot', 'Contains vegetable solids; all vegetables are avoided.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (227, 'Lemongrass', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (228, 'Lentils', 'cannot', 'Lentils are high in fibre and leave residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (229, 'Lettuce', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (230, 'Mango', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (231, 'Mee kia', 'can', 'Noodles are allowed if plain and not wholegrain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (232, 'Mee pok', 'can', 'Noodles are allowed if plain and not wholegrain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (233, 'Mee sua', 'can', 'Noodles are allowed if plain and not wholegrain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (234, 'Milo', 'cannot', 'Malted drinks are avoided on this hospital’s fluid list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (235, 'Mixed nuts', 'cannot', 'Nuts leave residue that is hard to clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (236, 'Mung beans', 'cannot', 'Beans are high in fibre and leave residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (237, 'Mushrooms', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (238, 'Mutton / lamb', 'cannot', 'Red meat is avoided on this hospital’s list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (239, 'Oats', 'cannot', 'High in fibre, which leaves residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (240, 'Okra', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (241, 'Onion', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (242, 'Orange', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (243, 'Papaya', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (244, 'Pasta', 'can', 'Counts as noodles/pasta-style refined starch if not wholegrain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (245, 'Peanuts', 'cannot', 'Nuts leave residue that is hard to clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (246, 'Pear', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (247, 'Pear juice', 'can', 'Light-coloured pear juice is allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (248, 'Peas', 'cannot', 'Peas/beans are high in fibre and leave residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (249, 'Pineapple', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (250, 'Plain biscuits', 'can', 'Plain biscuits are low in fibre and allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (251, 'Plain tea', 'cannot', 'Dark coffee/tea is avoided because it can affect the bowel view.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (252, 'Pork', 'can', 'Pork is listed as an allowed meat option.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (253, 'Potato', 'cannot', 'Low-fibre starch if peeled; do not eat the skin.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (254, 'Prawns', 'can', 'Shellfish such as prawns are allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (255, 'Prune juice', 'cannot', 'Dark-coloured liquids can stain the bowel view — avoid.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (256, 'Prunes', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (257, 'Pumpkin', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (258, 'Pumpkin seeds', 'cannot', 'Seeds leave residue that is hard to clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (259, 'Putu mayam', 'can', 'Rice noodle cake listed as an allowed rice alternative.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (260, 'Raisins', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (261, 'Red beans', 'cannot', 'Beans are high in fibre and leave residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (262, 'Rice cereal', 'can', 'Rice cereal is listed as an allowed refined option.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (263, 'Sambal', 'cannot', 'Contains chilli/vegetable solids; all vegetables are avoided.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (264, 'Seaweed', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (265, 'Sesame seeds', 'cannot', 'Seeds leave residue that is hard to clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (266, 'Shellfish', 'can', 'Shellfish is allowed (e.g. prawns).', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (267, 'Smooth peanut butter', 'cannot', 'Nuts and nut products are avoided on this hospital’s list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (268, 'Soy bean drink', 'cannot', 'Soy milk drinks are avoided on this hospital’s fluid list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (269, 'Soy milk', 'cannot', 'Soy milk is avoided on this hospital’s fluid list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (270, 'Soybeans', 'cannot', 'Beans are high in fibre and leave residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (271, 'Spinach', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (272, 'Spring onion', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (273, 'Squid', 'can', 'Shellfish/seafood is allowed if plain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (274, 'Sunflower seeds', 'cannot', 'Seeds leave residue that is hard to clear.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (275, 'Sweet chilli sauce', 'cannot', 'Contains chilli/vegetable solids; all vegetables are avoided.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (276, 'Sweet potato', 'cannot', 'Only if peeled and well-cooked.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (277, 'Taukwa', 'can', 'Taukwa is listed as an allowed protein.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (278, 'Teh', 'cannot', 'Coffee/tea is avoided; milk drinks are also not allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (279, 'Teh tarik', 'cannot', 'Coffee/tea is avoided; milk drinks are also not allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (280, 'Teh-C', 'cannot', 'Coffee/tea is avoided; milk drinks are also not allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (281, 'Teh-O', 'cannot', 'Dark coffee/tea is avoided because it can affect the bowel view.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (282, 'Tempeh', 'cannot', 'Tempeh is high in fibre and listed to avoid.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (283, 'Tofu', 'can', 'Tofu is listed as an allowed protein.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (284, 'Tomato', 'cannot', 'All vegetables are avoided because their fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (285, 'Tomato juice', 'cannot', 'Red-coloured liquids can stain the bowel view — avoid.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (286, 'Vegetarian mock meat', 'can', 'Vegetarian mock meat is listed as allowed.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (287, 'Water', 'can', 'Clear fluid that leaves no residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (288, 'Watermelon', 'cannot', 'All fruits are avoided because fruit fibre leaves residue.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (289, 'White bread', 'can', 'Low in fibre if plain white bread.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (290, 'White porridge', 'can', 'Low in fibre, so it leaves little residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (291, 'White rice', 'can', 'Low in fibre, so it leaves little residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (292, 'Wholegrain biscuits', 'cannot', 'High-fibre biscuits leave residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (293, 'Wholegrain bread', 'cannot', 'High in fibre, which leaves residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (294, 'Wholemeal / wholegrain biscuits', 'cannot', 'High-fibre biscuits leave residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (295, 'Wholemeal biscuits', 'cannot', 'High-fibre biscuits leave residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (296, 'Wholemeal bread', 'cannot', 'High in fibre, which leaves residue in the bowel.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (297, 'Yam / taro', 'cannot', 'Only if peeled and well-cooked.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (298, 'Yellow noodles', 'can', 'Noodles are allowed if plain and not wholegrain.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (299, 'Yoghurt', 'cannot', 'Yoghurt is avoided on this hospital’s low-residue list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (300, 'Yoghurt drinks', 'cannot', 'Yoghurt drinks are avoided on this hospital’s fluid list.', 'SKH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (301, 'Apple', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (302, 'Banana', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (303, 'Barley', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (304, 'Barley water', 'cannot', 'Barley is a high-fibre grain and is grouped with foods to avoid.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (305, 'Bean sprouts', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (306, 'Bee hoon', 'can', 'Refined noodles are low in fibre if plain.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (307, 'Berries', 'cannot', 'Fruit fibre and seeds leave residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (308, 'Bitter gourd', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (309, 'Black coffee', 'can', 'Coffee/tea is allowed in the low-fibre phase, with or without milk.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (310, 'Bran cereal', 'cannot', 'Very high in fibre, which leaves a lot of residue.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (311, 'Broccoli', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (312, 'Brown rice', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (313, 'Brown rice porridge', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (314, 'Cabbage', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (315, 'Carrot', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (316, 'Cauliflower', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (317, 'Chapati', 'cannot', 'Usually higher-fibre flour, which leaves more residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (318, 'Chicken', 'can', 'Lean chicken is low in fibre and leaves little residue.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (319, 'Chilli', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (320, 'Chye sim', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (321, 'Clear chicken broth', 'can', 'Clear soup leaves little residue if it stays clear and light.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (322, 'Clear fish broth', 'can', 'Clear soup leaves little residue if it stays clear and light.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (323, 'Clear soup', 'can', 'Clear soup leaves little residue if it stays clear and light with no solids.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (324, 'Coriander', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (325, 'Corn', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (326, 'Cucumber', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (327, 'Curry paste', 'cannot', 'Contains vegetable solids; vegetables are avoided.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (328, 'Dried fruit', 'cannot', 'Concentrated fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (329, 'Egg', 'can', 'Eggs are low in fibre and leave little residue.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (330, 'Eggplant', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (331, 'Fish', 'can', 'Lean fish is low in fibre and leaves little residue.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (332, 'French beans', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (333, 'Fried shallots', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (334, 'Garlic', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (335, 'Ginger', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (336, 'Grapes', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (337, 'Guava', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (338, 'Honeydew', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (339, 'Kai lan', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (340, 'Kang kong', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (341, 'Kopi', 'can', 'Coffee/tea with milk is allowed in the low-fibre phase.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (342, 'Kopi-C', 'can', 'Coffee/tea with milk is allowed in the low-fibre phase.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (343, 'Kopi-O', 'can', 'Coffee/tea is allowed in the low-fibre phase, with or without milk.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (344, 'Kway teow', 'can', 'Refined noodles are low in fibre if plain.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (345, 'Laksa leaves', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (346, 'Laksa paste', 'cannot', 'Contains vegetable solids; vegetables are avoided.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (347, 'Lemongrass', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (348, 'Lettuce', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (349, 'Mango', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (350, 'Mee sua', 'can', 'Refined noodles are low in fibre if plain.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (351, 'Muesli', 'cannot', 'High in fibre from grains and extras, which leave residue.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (352, 'Mushrooms', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (353, 'Oats', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (354, 'Okra', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (355, 'Onion', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (356, 'Orange', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (357, 'Papaya', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (358, 'Pear', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (359, 'Pineapple', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (360, 'Plain tea', 'can', 'Coffee/tea is allowed in the low-fibre phase, with or without milk.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (361, 'Popcorn', 'cannot', 'Hulls and fibre leave residue that is hard to clear.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (362, 'Potato', 'cannot', 'Low-fibre starch if peeled; do not eat the skin.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (363, 'Prunes', 'cannot', 'Concentrated fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (364, 'Pumpkin', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (365, 'Raisins', 'cannot', 'Concentrated fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (366, 'Sambal', 'cannot', 'Contains chilli/vegetable solids; vegetables are avoided.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (367, 'Seaweed', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (368, 'Spinach', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (369, 'Spring onion', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (370, 'Sweet chilli sauce', 'cannot', 'Contains chilli/vegetable solids; vegetables are avoided.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (371, 'Sweet potato', 'cannot', 'Only if peeled and well-cooked.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (372, 'Teh', 'can', 'Coffee/tea with milk is allowed in the low-fibre phase.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (373, 'Teh tarik', 'can', 'Coffee/tea with milk is allowed in the low-fibre phase.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (374, 'Teh-C', 'can', 'Coffee/tea with milk is allowed in the low-fibre phase.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (375, 'Teh-O', 'can', 'Coffee/tea is allowed in the low-fibre phase, with or without milk.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (376, 'Tomato', 'cannot', 'Vegetables are avoided because their fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (377, 'Watermelon', 'cannot', 'Fruit fibre leaves residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (378, 'White bread', 'can', 'Low in fibre if plain white bread with no spread.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (379, 'White porridge', 'can', 'Low in fibre, so it leaves little residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (380, 'White rice', 'can', 'Low in fibre, so it leaves little residue in the bowel.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (381, 'Wholegrain bread', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (382, 'Wholemeal bread', 'cannot', 'High in fibre, which leaves residue and can hide the bowel lining.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (383, 'Yam / taro', 'cannot', 'Only if peeled and well-cooked.', 'TTSH', 'Ingredient Tab Rows Sept 18 2026.csv'),
  (384, 'Beef', 'cannot', 'Red meat is harder to digest and leaves more residue than lean protein.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (385, 'Butter', 'review', 'Fat itself is low in fibre, but how much is used in cooking is hard to judge.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (386, 'Calamansi drink', 'cannot', 'Pulp and bits leave residue in the bowel.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (387, 'Chin chow drink', 'cannot', 'Dark and cloudy, so it does not meet the clear-liquid rule.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (388, 'Coconut flesh', 'review', 'Coconut flesh is fibrous, unlike coconut milk.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (389, 'Coconut water', 'cannot', 'Pulp and bits leave residue in the bowel.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (390, 'Cooking oil', 'review', 'Fat itself is low in fibre, but how much is used in cooking is hard to judge.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (391, 'Duck', 'cannot', 'Red meat is harder to digest and leaves more residue than lean protein.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (392, 'Mutton / lamb', 'cannot', 'Red meat is harder to digest and leaves more residue than lean protein.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (393, 'Plain prata', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (394, 'Pork', 'can', 'Low-fibre protein if soft and well-cooked.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (395, 'Sugarcane juice', 'cannot', 'Pulp and bits leave residue in the bowel.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (396, 'Tempeh', 'cannot', 'High in fibre and leaves residue that is hard to clear.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (397, 'Unlisted extras (recipe varies)', 'review', 'Recipe varies, so the extras cannot be checked individually.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (398, 'Vegetarian mock meat', 'review', 'Recipe and fibre content vary by brand.', 'DIETICIAN', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (399, 'Bandung', 'review', 'Milk-based and pink-coloured; both can be restricted.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (400, 'Butter', 'review', 'Fat itself is low in fibre, but how much is used in cooking is hard to judge.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (401, 'Coconut flesh', 'review', 'Coconut flesh is fibrous, unlike coconut milk.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (402, 'Cooking oil', 'review', 'Fat itself is low in fibre, but how much is used in cooking is hard to judge.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (403, 'Plain crackers', 'can', 'Refined starch that is low in fibre.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (404, 'Plain naan', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (405, 'Plain pancake', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (406, 'Plain prata', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (407, 'Plain waffle', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'SKH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (408, 'Bandung', 'review', 'Milk-based and pink-coloured; both can be restricted.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (409, 'Butter', 'review', 'Fat itself is low in fibre, but how much is used in cooking is hard to judge.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (410, 'Coconut flesh', 'review', 'Coconut flesh is fibrous, unlike coconut milk.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (411, 'Cooking oil', 'review', 'Fat itself is low in fibre, but how much is used in cooking is hard to judge.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (412, 'Plain biscuits', 'can', 'Refined starch that is low in fibre.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (413, 'Plain crackers', 'can', 'Refined starch that is low in fibre.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (414, 'Plain naan', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (415, 'Plain pancake', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (416, 'Plain prata', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (417, 'Plain waffle', 'review', 'Refined flour is low in fibre, but the ghee or oil used can matter.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet'),
  (418, 'Rice cereal', 'can', 'Refined starch that is low in fibre.', 'TTSH', 'UAT dataset (hackathon, requires clinical validation) — name carried by a dish but absent from the Sept 18 2026 sheet');

-- Move the identity sequence past the ids written above.
SELECT setval(pg_get_serial_sequence('ingredient_tab', 'id'), 418, true);

