DELETE FROM dishes_tab;

INSERT INTO dishes_tab (name, meal_type, source_hospital, ingredient_list, hard_no, hard_no_reason)
VALUES
    -- --- DIETICIAN tier (225 dishes) ---
  ('Potato', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 109, "name": "Potato"}]'::jsonb, false, ''),
  ('Sweet potato', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 140, "name": "Sweet potato"}]'::jsonb, false, ''),
  ('Yam / taro', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 164, "name": "Yam / taro"}]'::jsonb, false, ''),
  ('Pork', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 394, "name": "Pork"}]'::jsonb, false, ''),
  ('Beef', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 384, "name": "Beef"}]'::jsonb, true, 'Red meat is harder to digest and leaves more residue than lean protein.'),
  ('Mutton / lamb', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 392, "name": "Mutton / lamb"}]'::jsonb, true, 'Red meat is harder to digest and leaves more residue than lean protein.'),
  ('Duck', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 391, "name": "Duck"}]'::jsonb, true, 'Red meat is harder to digest and leaves more residue than lean protein.'),
  ('Fishball', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 48, "name": "Fishball"}]'::jsonb, false, ''),
  ('Fishcake', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 49, "name": "Fishcake"}]'::jsonb, false, ''),
  ('Sausage', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 121, "name": "Sausage"}]'::jsonb, false, ''),
  ('Luncheon meat', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 82, "name": "Luncheon meat"}]'::jsonb, false, ''),
  ('Vegetarian mock meat', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 398, "name": "Vegetarian mock meat"}]'::jsonb, false, ''),
  ('Tofu', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 147, "name": "Tofu"}]'::jsonb, false, ''),
  ('Taukwa', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 142, "name": "Taukwa"}]'::jsonb, false, ''),
  ('Tau pok', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 141, "name": "Tau pok"}]'::jsonb, false, ''),
  ('Tempeh', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 396, "name": "Tempeh"}]'::jsonb, true, 'High in fibre and leaves residue that is hard to clear.'),
  ('Soybeans', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 133, "name": "Soybeans"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Red beans', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 118, "name": "Red beans"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Mung beans', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 91, "name": "Mung beans"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Chickpeas', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 25, "name": "Chickpeas"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Lentils', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 80, "name": "Lentils"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Peas', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 105, "name": "Peas"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Peanuts', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 102, "name": "Peanuts"}]'::jsonb, true, 'High in fibre; nut pieces leave residue in the bowel.'),
  ('Sesame seeds', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 123, "name": "Sesame seeds"}]'::jsonb, true, 'Tiny seeds leave residue and are hard to clear.'),
  ('Chia seeds', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 23, "name": "Chia seeds"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Flax seeds', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 50, "name": "Flax seeds"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Sunflower seeds', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 138, "name": "Sunflower seeds"}]'::jsonb, true, 'Seed pieces leave residue in the bowel.'),
  ('Pumpkin seeds', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 115, "name": "Pumpkin seeds"}]'::jsonb, true, 'Seed pieces leave residue in the bowel.'),
  ('Mixed nuts', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 89, "name": "Mixed nuts"}]'::jsonb, true, 'Nut pieces leave residue in the bowel.'),
  ('Smooth peanut butter', ARRAY['lunch', 'dinner', 'snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 128, "name": "Smooth peanut butter"}]'::jsonb, false, ''),
  ('Cucumber', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 39, "name": "Cucumber"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Tomato', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 148, "name": "Tomato"}]'::jsonb, true, 'Vegetable fibre and seeds leave residue in the bowel.'),
  ('Carrot', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 19, "name": "Carrot"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Pumpkin', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 114, "name": "Pumpkin"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Cabbage', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 18, "name": "Cabbage"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Chye sim', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 27, "name": "Chye sim"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Kai lan', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 70, "name": "Kai lan"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Kang kong', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 71, "name": "Kang kong"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Spinach', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 134, "name": "Spinach"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Lettuce', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 81, "name": "Lettuce"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Bean sprouts', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 7, "name": "Bean sprouts"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Broccoli', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 14, "name": "Broccoli"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Cauliflower', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 20, "name": "Cauliflower"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('French beans', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 51, "name": "French beans"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Okra', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 95, "name": "Okra"}]'::jsonb, true, 'Vegetable fibre and seeds leave residue in the bowel.'),
  ('Eggplant', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 45, "name": "Eggplant"}]'::jsonb, true, 'Vegetable fibre leaves residue in the bowel.'),
  ('Bitter gourd', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 10, "name": "Bitter gourd"}]'::jsonb, true, 'Vegetable fibre and seeds leave residue in the bowel.'),
  ('Mushrooms', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 92, "name": "Mushrooms"}]'::jsonb, true, 'Very high in fibre and leave a lot of residue.'),
  ('Seaweed', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 122, "name": "Seaweed"}]'::jsonb, true, 'Fibrous and leaves residue in the bowel.'),
  ('Onion', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 96, "name": "Onion"}]'::jsonb, true, 'Vegetable pieces leave residue.'),
  ('Garlic', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 56, "name": "Garlic"}]'::jsonb, true, 'Vegetable pieces leave residue.'),
  ('Ginger', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 57, "name": "Ginger"}]'::jsonb, true, 'Vegetable pieces leave residue.'),
  ('Chilli', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 26, "name": "Chilli"}]'::jsonb, true, 'Seeds and vegetable solids leave residue in the bowel.'),
  ('Spring onion', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 135, "name": "Spring onion"}]'::jsonb, true, 'Garnish pieces add fibre — remove them.'),
  ('Coriander', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 36, "name": "Coriander"}]'::jsonb, true, 'Garnish pieces add fibre — remove them.'),
  ('Laksa leaves', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 77, "name": "Laksa leaves"}]'::jsonb, true, 'Herb leaves add fibre and residue — avoid.'),
  ('Lemongrass', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 79, "name": "Lemongrass"}]'::jsonb, false, ''),
  ('Fried shallots', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 54, "name": "Fried shallots"}]'::jsonb, true, 'Crunchy garnish adds fibre — remove them.'),
  ('Corn', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 37, "name": "Corn"}]'::jsonb, true, 'Kernels and fibre leave residue that is hard to clear.'),
  ('Soy sauce', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 132, "name": "Soy sauce"}]'::jsonb, false, ''),
  ('Dark soy sauce', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 42, "name": "Dark soy sauce"}]'::jsonb, false, ''),
  ('Oyster sauce', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 99, "name": "Oyster sauce"}]'::jsonb, false, ''),
  ('Tomato ketchup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 150, "name": "Tomato ketchup"}]'::jsonb, false, ''),
  ('Sweet chilli sauce', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 139, "name": "Sweet chilli sauce"}]'::jsonb, true, 'Often contains seeds or vegetable pieces that leave residue — preferably avoid.'),
  ('Sambal', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 120, "name": "Sambal"}]'::jsonb, true, 'Often contains chilli seeds or solids that leave residue — preferably avoid.'),
  ('Curry paste', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 40, "name": "Curry paste"}]'::jsonb, true, 'Usually contains chilli and vegetable solids that leave residue.'),
  ('Laksa paste', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 78, "name": "Laksa paste"}]'::jsonb, true, 'Usually contains chilli, herbs and solids that leave residue.'),
  ('Banana', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 4, "name": "Banana"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Papaya', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 100, "name": "Papaya"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Watermelon', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 154, "name": "Watermelon"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Apple', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 2, "name": "Apple"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Orange', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 97, "name": "Orange"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Pineapple', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 106, "name": "Pineapple"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Mango', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 83, "name": "Mango"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Guava', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 61, "name": "Guava"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Pear', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 103, "name": "Pear"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Grapes', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 60, "name": "Grapes"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Berries', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 9, "name": "Berries"}]'::jsonb, true, 'Seeds and fibre leave residue that is hard to clear.'),
  ('Dried fruit', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 43, "name": "Dried fruit"}]'::jsonb, true, 'Concentrated fruit fibre leaves residue in the bowel.'),
  ('Raisins', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 117, "name": "Raisins"}]'::jsonb, true, 'Concentrated fruit fibre leaves residue in the bowel.'),
  ('Prunes', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 112, "name": "Prunes"}]'::jsonb, true, 'High in fibre and leave residue in the bowel.'),
  ('Honeydew', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 64, "name": "Honeydew"}]'::jsonb, true, 'Fruit fibre leaves residue in the bowel.'),
  ('Water', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 153, "name": "Water"}]'::jsonb, false, ''),
  ('Clear chicken broth', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 28, "name": "Clear chicken broth"}]'::jsonb, false, ''),
  ('Clear fish broth', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 29, "name": "Clear fish broth"}]'::jsonb, false, ''),
  ('Colourless soft drink', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 34, "name": "Colourless soft drink"}]'::jsonb, false, ''),
  ('Glucose drink', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 58, "name": "Glucose drink"}]'::jsonb, false, ''),
  ('Honey water', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 63, "name": "Honey water"}]'::jsonb, false, ''),
  ('Apple juice (clear, no pulp)', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 3, "name": "Apple juice"}]'::jsonb, false, ''),
  ('Pear juice (clear, no pulp)', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 104, "name": "Pear juice"}]'::jsonb, false, ''),
  ('Orange juice', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 98, "name": "Orange juice"}]'::jsonb, false, ''),
  ('Sugarcane juice', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 395, "name": "Sugarcane juice"}]'::jsonb, true, 'Pulp and bits leave residue in the bowel.'),
  ('Calamansi drink', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 386, "name": "Calamansi drink"}]'::jsonb, true, 'Pulp and bits leave residue in the bowel.'),
  ('Coconut water', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 389, "name": "Coconut water"}]'::jsonb, true, 'Pulp and bits leave residue in the bowel.'),
  ('Grape juice', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 59, "name": "Grape juice"}]'::jsonb, true, 'Dark colour can stain the bowel and look like blood during the scope.'),
  ('Prune juice', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 111, "name": "Prune juice"}]'::jsonb, true, 'Contains fibre and is dark — avoid.'),
  ('Tomato juice', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 149, "name": "Tomato juice"}]'::jsonb, true, 'Pulpy and coloured; can leave residue or stain the view — avoid.'),
  ('Milo', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 88, "name": "Milo"}]'::jsonb, false, ''),
  ('Horlicks', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 65, "name": "Horlicks"}]'::jsonb, false, ''),
  ('Isotonic drink (light-coloured)', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 66, "name": "Isotonic drink (light-coloured)"}]'::jsonb, false, ''),
  ('Isotonic drink (red/purple/blue)', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 67, "name": "Isotonic drink (red/purple/blue)"}]'::jsonb, true, 'Dark colours can stain the bowel and look like blood during the scope.'),
  ('Chin chow drink', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 387, "name": "Chin chow drink"}]'::jsonb, true, 'Dark and cloudy, so it does not meet the clear-liquid rule.'),
  ('Jelly', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 68, "name": "Jelly"}]'::jsonb, false, ''),
  ('Agar-agar', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 1, "name": "Agar-agar"}]'::jsonb, false, ''),
  ('Chicken rice', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 39, "name": "Cucumber"}, {"id": 26, "name": "Chilli"}, {"id": 132, "name": "Soy sauce"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Roasted chicken rice', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 39, "name": "Cucumber"}, {"id": 132, "name": "Soy sauce"}, {"id": 26, "name": "Chilli"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Steamed chicken rice', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 39, "name": "Cucumber"}, {"id": 132, "name": "Soy sauce"}, {"id": 26, "name": "Chilli"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Roast duck rice', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 391, "name": "Duck"}, {"id": 39, "name": "Cucumber"}, {"id": 42, "name": "Dark soy sauce"}]'::jsonb, false, ''),
  ('Char siu rice', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 394, "name": "Pork"}, {"id": 39, "name": "Cucumber"}]'::jsonb, false, ''),
  ('Economic rice / cai png', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 397, "name": "Unlisted extras (recipe varies)"}]'::jsonb, false, ''),
  ('Fried rice', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 44, "name": "Egg"}, {"id": 105, "name": "Peas"}, {"id": 135, "name": "Spring onion"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Char kway teow', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 76, "name": "Kway teow"}, {"id": 44, "name": "Egg"}, {"id": 110, "name": "Prawns"}, {"id": 49, "name": "Fishcake"}, {"id": 7, "name": "Bean sprouts"}, {"id": 135, "name": "Spring onion"}, {"id": 42, "name": "Dark soy sauce"}, {"id": 26, "name": "Chilli"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Hokkien mee', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 8, "name": "Bee hoon"}, {"id": 110, "name": "Prawns"}, {"id": 136, "name": "Squid"}, {"id": 394, "name": "Pork"}, {"id": 7, "name": "Bean sprouts"}, {"id": 135, "name": "Spring onion"}, {"id": 120, "name": "Sambal"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Prawn mee', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 8, "name": "Bee hoon"}, {"id": 110, "name": "Prawns"}, {"id": 394, "name": "Pork"}, {"id": 7, "name": "Bean sprouts"}, {"id": 71, "name": "Kang kong"}, {"id": 26, "name": "Chilli"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Fishball noodles', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 86, "name": "Mee pok"}, {"id": 85, "name": "Mee kia"}, {"id": 48, "name": "Fishball"}, {"id": 49, "name": "Fishcake"}, {"id": 81, "name": "Lettuce"}, {"id": 7, "name": "Bean sprouts"}, {"id": 26, "name": "Chilli"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Bak chor mee', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 86, "name": "Mee pok"}, {"id": 85, "name": "Mee kia"}, {"id": 394, "name": "Pork"}, {"id": 48, "name": "Fishball"}, {"id": 92, "name": "Mushrooms"}, {"id": 81, "name": "Lettuce"}, {"id": 26, "name": "Chilli"}, {"id": 135, "name": "Spring onion"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Wanton noodles', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 394, "name": "Pork"}, {"id": 27, "name": "Chye sim"}, {"id": 26, "name": "Chilli"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Lor mee', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 44, "name": "Egg"}, {"id": 49, "name": "Fishcake"}, {"id": 394, "name": "Pork"}, {"id": 7, "name": "Bean sprouts"}, {"id": 26, "name": "Chilli"}, {"id": 36, "name": "Coriander"}, {"id": 56, "name": "Garlic"}]'::jsonb, false, ''),
  ('Beef hor fun', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 76, "name": "Kway teow"}, {"id": 384, "name": "Beef"}, {"id": 70, "name": "Kai lan"}, {"id": 27, "name": "Chye sim"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Sliced fish bee hoon', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 8, "name": "Bee hoon"}, {"id": 47, "name": "Fish"}, {"id": 148, "name": "Tomato"}, {"id": 52, "name": "Fresh milk"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Fish soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 47, "name": "Fish"}, {"id": 148, "name": "Tomato"}, {"id": 28, "name": "Clear chicken broth"}, {"id": 54, "name": "Fried shallots"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Chicken soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 28, "name": "Clear chicken broth"}, {"id": 397, "name": "Unlisted extras (recipe varies)"}]'::jsonb, false, ''),
  ('Congee', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 156, "name": "White porridge"}, {"id": 135, "name": "Spring onion"}, {"id": 57, "name": "Ginger"}, {"id": 132, "name": "Soy sauce"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Fish porridge', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 156, "name": "White porridge"}, {"id": 47, "name": "Fish"}, {"id": 135, "name": "Spring onion"}, {"id": 57, "name": "Ginger"}, {"id": 132, "name": "Soy sauce"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Chicken porridge', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 156, "name": "White porridge"}, {"id": 24, "name": "Chicken"}, {"id": 135, "name": "Spring onion"}, {"id": 57, "name": "Ginger"}, {"id": 132, "name": "Soy sauce"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Century egg porridge', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 156, "name": "White porridge"}, {"id": 44, "name": "Egg"}, {"id": 394, "name": "Pork"}, {"id": 135, "name": "Spring onion"}, {"id": 57, "name": "Ginger"}, {"id": 132, "name": "Soy sauce"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Claypot rice', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 121, "name": "Sausage"}, {"id": 92, "name": "Mushrooms"}, {"id": 27, "name": "Chye sim"}, {"id": 42, "name": "Dark soy sauce"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Bak kut teh', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 394, "name": "Pork"}, {"id": 56, "name": "Garlic"}, {"id": 36, "name": "Coriander"}]'::jsonb, false, ''),
  ('Pig organ soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 394, "name": "Pork"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Steamed fish', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 47, "name": "Fish"}, {"id": 57, "name": "Ginger"}, {"id": 135, "name": "Spring onion"}, {"id": 132, "name": "Soy sauce"}, {"id": 36, "name": "Coriander"}]'::jsonb, false, ''),
  ('Sweet and sour fish', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 47, "name": "Fish"}, {"id": 96, "name": "Onion"}, {"id": 106, "name": "Pineapple"}]'::jsonb, false, ''),
  ('Black pepper beef', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 384, "name": "Beef"}, {"id": 96, "name": "Onion"}]'::jsonb, false, ''),
  ('Beef noodles', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 384, "name": "Beef"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Kway chap', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 76, "name": "Kway teow"}, {"id": 394, "name": "Pork"}, {"id": 42, "name": "Dark soy sauce"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Roast meats platter', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 394, "name": "Pork"}, {"id": 391, "name": "Duck"}, {"id": 24, "name": "Chicken"}, {"id": 39, "name": "Cucumber"}]'::jsonb, false, ''),
  ('Har gow', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 110, "name": "Prawns"}, {"id": 397, "name": "Unlisted extras (recipe varies)"}]'::jsonb, false, ''),
  ('Siew mai', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 394, "name": "Pork"}, {"id": 110, "name": "Prawns"}, {"id": 397, "name": "Unlisted extras (recipe varies)"}]'::jsonb, false, ''),
  ('Chee cheong fun', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 132, "name": "Soy sauce"}, {"id": 123, "name": "Sesame seeds"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Chai tow kway / carrot cake', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 44, "name": "Egg"}, {"id": 135, "name": "Spring onion"}, {"id": 42, "name": "Dark soy sauce"}, {"id": 132, "name": "Soy sauce"}, {"id": 26, "name": "Chilli"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Popiah', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 44, "name": "Egg"}, {"id": 110, "name": "Prawns"}, {"id": 81, "name": "Lettuce"}, {"id": 7, "name": "Bean sprouts"}, {"id": 102, "name": "Peanuts"}, {"id": 26, "name": "Chilli"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Rojak', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 147, "name": "Tofu"}, {"id": 390, "name": "Cooking oil"}, {"id": 39, "name": "Cucumber"}, {"id": 106, "name": "Pineapple"}, {"id": 102, "name": "Peanuts"}]'::jsonb, false, ''),
  ('Satay', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 24, "name": "Chicken"}, {"id": 394, "name": "Pork"}, {"id": 384, "name": "Beef"}, {"id": 392, "name": "Mutton / lamb"}, {"id": 39, "name": "Cucumber"}, {"id": 96, "name": "Onion"}, {"id": 102, "name": "Peanuts"}]'::jsonb, false, ''),
  ('Chilli crab', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 124, "name": "Shellfish"}, {"id": 26, "name": "Chilli"}, {"id": 148, "name": "Tomato"}, {"id": 150, "name": "Tomato ketchup"}]'::jsonb, false, ''),
  ('Cereal prawns', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 390, "name": "Cooking oil"}, {"id": 110, "name": "Prawns"}, {"id": 26, "name": "Chilli"}, {"id": 385, "name": "Butter"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Ngoh hiang', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 394, "name": "Pork"}, {"id": 110, "name": "Prawns"}, {"id": 96, "name": "Onion"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Nasi lemak', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 33, "name": "Coconut milk"}, {"id": 44, "name": "Egg"}, {"id": 24, "name": "Chicken"}, {"id": 47, "name": "Fish"}, {"id": 39, "name": "Cucumber"}, {"id": 102, "name": "Peanuts"}, {"id": 120, "name": "Sambal"}]'::jsonb, false, ''),
  ('Nasi padang', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 40, "name": "Curry paste"}, {"id": 120, "name": "Sambal"}]'::jsonb, false, ''),
  ('Mee rebus', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 44, "name": "Egg"}, {"id": 7, "name": "Bean sprouts"}, {"id": 27, "name": "Chye sim"}, {"id": 140, "name": "Sweet potato"}, {"id": 26, "name": "Chilli"}, {"id": 54, "name": "Fried shallots"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Mee siam', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 8, "name": "Bee hoon"}, {"id": 44, "name": "Egg"}, {"id": 110, "name": "Prawns"}, {"id": 7, "name": "Bean sprouts"}, {"id": 135, "name": "Spring onion"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Malay mee goreng', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 44, "name": "Egg"}, {"id": 24, "name": "Chicken"}, {"id": 18, "name": "Cabbage"}, {"id": 148, "name": "Tomato"}, {"id": 139, "name": "Sweet chilli sauce"}, {"id": 135, "name": "Spring onion"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Ayam penyet', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 390, "name": "Cooking oil"}, {"id": 39, "name": "Cucumber"}, {"id": 18, "name": "Cabbage"}, {"id": 120, "name": "Sambal"}]'::jsonb, false, ''),
  ('Ayam bakar', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 39, "name": "Cucumber"}, {"id": 81, "name": "Lettuce"}, {"id": 120, "name": "Sambal"}]'::jsonb, false, ''),
  ('Mee soto', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 24, "name": "Chicken"}, {"id": 7, "name": "Bean sprouts"}, {"id": 26, "name": "Chilli"}, {"id": 135, "name": "Spring onion"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Soto ayam', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 24, "name": "Chicken"}, {"id": 7, "name": "Bean sprouts"}, {"id": 18, "name": "Cabbage"}, {"id": 26, "name": "Chilli"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Lontong', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 44, "name": "Egg"}, {"id": 18, "name": "Cabbage"}, {"id": 51, "name": "French beans"}, {"id": 33, "name": "Coconut milk"}, {"id": 120, "name": "Sambal"}]'::jsonb, false, ''),
  ('Sup tulang', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 155, "name": "White bread"}, {"id": 157, "name": "White rice"}, {"id": 392, "name": "Mutton / lamb"}, {"id": 96, "name": "Onion"}, {"id": 148, "name": "Tomato"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Beef rendang', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 384, "name": "Beef"}, {"id": 33, "name": "Coconut milk"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Chicken rendang', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 33, "name": "Coconut milk"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Assam fish', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 47, "name": "Fish"}, {"id": 95, "name": "Okra"}, {"id": 148, "name": "Tomato"}, {"id": 26, "name": "Chilli"}]'::jsonb, false, ''),
  ('Otah', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 47, "name": "Fish"}, {"id": 26, "name": "Chilli"}, {"id": 33, "name": "Coconut milk"}, {"id": 40, "name": "Curry paste"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Begedil', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 109, "name": "Potato"}, {"id": 44, "name": "Egg"}, {"id": 394, "name": "Pork"}, {"id": 96, "name": "Onion"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Egg prata', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 393, "name": "Plain prata"}, {"id": 44, "name": "Egg"}, {"id": 40, "name": "Curry paste"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Onion prata', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 393, "name": "Plain prata"}, {"id": 96, "name": "Onion"}, {"id": 40, "name": "Curry paste"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Cheese prata', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 393, "name": "Plain prata"}, {"id": 22, "name": "Cheese"}, {"id": 40, "name": "Curry paste"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Thosai / dosa', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 80, "name": "Lentils"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Idli', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 80, "name": "Lentils"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Idiyappam / putu mayam', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 8, "name": "Bee hoon"}, {"id": 33, "name": "Coconut milk"}, {"id": 388, "name": "Coconut flesh"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Appam', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 33, "name": "Coconut milk"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Naan', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 155, "name": "White bread"}, {"id": 385, "name": "Butter"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Tandoori chicken', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 24, "name": "Chicken"}, {"id": 166, "name": "Yoghurt"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Biryani', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 392, "name": "Mutton / lamb"}, {"id": 96, "name": "Onion"}, {"id": 166, "name": "Yoghurt"}, {"id": 390, "name": "Cooking oil"}]'::jsonb, false, ''),
  ('Murtabak', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 392, "name": "Mutton / lamb"}, {"id": 24, "name": "Chicken"}, {"id": 96, "name": "Onion"}, {"id": 40, "name": "Curry paste"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Indian mee goreng', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 44, "name": "Egg"}, {"id": 394, "name": "Pork"}, {"id": 18, "name": "Cabbage"}, {"id": 148, "name": "Tomato"}, {"id": 26, "name": "Chilli"}, {"id": 150, "name": "Tomato ketchup"}, {"id": 135, "name": "Spring onion"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Fish curry', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 47, "name": "Fish"}, {"id": 95, "name": "Okra"}, {"id": 148, "name": "Tomato"}, {"id": 96, "name": "Onion"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Chicken curry', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 109, "name": "Potato"}, {"id": 96, "name": "Onion"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Fish head curry', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 47, "name": "Fish"}, {"id": 95, "name": "Okra"}, {"id": 45, "name": "Eggplant"}, {"id": 148, "name": "Tomato"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Dhal', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 80, "name": "Lentils"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Samosa', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 109, "name": "Potato"}, {"id": 105, "name": "Peas"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Vadai', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 80, "name": "Lentils"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Laksa', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 8, "name": "Bee hoon"}, {"id": 110, "name": "Prawns"}, {"id": 49, "name": "Fishcake"}, {"id": 44, "name": "Egg"}, {"id": 7, "name": "Bean sprouts"}, {"id": 39, "name": "Cucumber"}, {"id": 33, "name": "Coconut milk"}, {"id": 78, "name": "Laksa paste"}, {"id": 26, "name": "Chilli"}, {"id": 77, "name": "Laksa leaves"}]'::jsonb, false, ''),
  ('Chicken buah keluak', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 89, "name": "Mixed nuts"}, {"id": 40, "name": "Curry paste"}]'::jsonb, false, ''),
  ('Chap chye', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 147, "name": "Tofu"}, {"id": 42, "name": "Dark soy sauce"}]'::jsonb, false, ''),
  ('Ayam pongteh', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 109, "name": "Potato"}, {"id": 133, "name": "Soybeans"}]'::jsonb, false, ''),
  ('Kaya toast', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 155, "name": "White bread"}, {"id": 72, "name": "Kaya"}, {"id": 385, "name": "Butter"}]'::jsonb, false, ''),
  ('Ice kacang', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 102, "name": "Peanuts"}, {"id": 68, "name": "Jelly"}, {"id": 37, "name": "Corn"}]'::jsonb, false, ''),
  ('Chendol', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 118, "name": "Red beans"}, {"id": 33, "name": "Coconut milk"}, {"id": 68, "name": "Jelly"}]'::jsonb, false, ''),
  ('Bubur cha cha', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 140, "name": "Sweet potato"}, {"id": 164, "name": "Yam / taro"}, {"id": 33, "name": "Coconut milk"}]'::jsonb, false, ''),
  ('Red bean soup', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 118, "name": "Red beans"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Green bean soup', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 91, "name": "Mung beans"}]'::jsonb, true, 'High in fibre and leave residue that is hard to clear.'),
  ('Peanut soup', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 102, "name": "Peanuts"}]'::jsonb, true, 'High in fibre; nut pieces leave residue in the bowel.'),
  ('Tau huay', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 147, "name": "Tofu"}, {"id": 397, "name": "Unlisted extras (recipe varies)"}]'::jsonb, false, ''),
  ('Mango pudding', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 83, "name": "Mango"}, {"id": 52, "name": "Fresh milk"}, {"id": 38, "name": "Cream"}]'::jsonb, false, ''),
  ('Onde-onde', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 388, "name": "Coconut flesh"}]'::jsonb, false, ''),
  ('Ang ku kueh', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 91, "name": "Mung beans"}, {"id": 102, "name": "Peanuts"}, {"id": 390, "name": "Cooking oil"}]'::jsonb, false, ''),
  ('Steamed rice kueh (plain)', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 397, "name": "Unlisted extras (recipe varies)"}]'::jsonb, false, ''),
  ('Clear broth', ARRAY['drink', 'lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 28, "name": "Clear chicken broth"}, {"id": 29, "name": "Clear fish broth"}]'::jsonb, false, ''),
  ('Milo drink', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 88, "name": "Milo"}]'::jsonb, false, ''),
  ('Horlicks drink', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 65, "name": "Horlicks"}]'::jsonb, false, ''),
  ('Apple juice', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 3, "name": "Apple juice"}]'::jsonb, false, ''),
  ('Pear juice', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 104, "name": "Pear juice"}]'::jsonb, false, ''),
  ('Chin chow', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 387, "name": "Chin chow drink"}]'::jsonb, true, 'Dark and cloudy, so it does not meet the clear-liquid rule.'),
  ('Isotonic drink (light colour)', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 66, "name": "Isotonic drink (light-coloured)"}]'::jsonb, false, ''),
  ('Soft drink (colourless)', ARRAY['drink']::dish_meal_type[], 'DIETICIAN', '[{"id": 34, "name": "Colourless soft drink"}]'::jsonb, false, ''),
  ('Jelly dessert', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 68, "name": "Jelly"}]'::jsonb, false, ''),
  ('Agar-agar dessert', ARRAY['snack']::dish_meal_type[], 'DIETICIAN', '[{"id": 1, "name": "Agar-agar"}]'::jsonb, false, ''),
  ('Plain toast', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 155, "name": "White bread"}]'::jsonb, false, ''),
  ('Soft-boiled eggs', ARRAY['breakfast']::dish_meal_type[], 'DIETICIAN', '[{"id": 44, "name": "Egg"}, {"id": 132, "name": "Soy sauce"}]'::jsonb, false, ''),
  ('Mee sua soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 87, "name": "Mee sua"}, {"id": 24, "name": "Chicken"}, {"id": 47, "name": "Fish"}, {"id": 44, "name": "Egg"}, {"id": 28, "name": "Clear chicken broth"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Kway teow soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 76, "name": "Kway teow"}, {"id": 48, "name": "Fishball"}, {"id": 49, "name": "Fishcake"}, {"id": 7, "name": "Bean sprouts"}, {"id": 81, "name": "Lettuce"}, {"id": 28, "name": "Clear chicken broth"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Bee hoon soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 8, "name": "Bee hoon"}, {"id": 24, "name": "Chicken"}, {"id": 47, "name": "Fish"}, {"id": 28, "name": "Clear chicken broth"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Yong tau foo soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 147, "name": "Tofu"}, {"id": 49, "name": "Fishcake"}, {"id": 28, "name": "Clear chicken broth"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Yong tau foo dry', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 147, "name": "Tofu"}, {"id": 49, "name": "Fishcake"}, {"id": 139, "name": "Sweet chilli sauce"}]'::jsonb, false, ''),
  ('Wonton soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 394, "name": "Pork"}, {"id": 110, "name": "Prawns"}, {"id": 28, "name": "Clear chicken broth"}, {"id": 135, "name": "Spring onion"}]'::jsonb, false, ''),
  ('Plain steamed egg', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 44, "name": "Egg"}, {"id": 132, "name": "Soy sauce"}]'::jsonb, false, ''),
  ('Omelette', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 44, "name": "Egg"}, {"id": 96, "name": "Onion"}, {"id": 390, "name": "Cooking oil"}]'::jsonb, false, ''),
  ('Fried chicken', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 24, "name": "Chicken"}, {"id": 390, "name": "Cooking oil"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Steamed tofu', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 147, "name": "Tofu"}, {"id": 135, "name": "Spring onion"}, {"id": 132, "name": "Soy sauce"}, {"id": 54, "name": "Fried shallots"}]'::jsonb, false, ''),
  ('Braised tofu', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 147, "name": "Tofu"}, {"id": 92, "name": "Mushrooms"}, {"id": 42, "name": "Dark soy sauce"}]'::jsonb, false, ''),
  ('Plain pasta', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 101, "name": "Pasta"}, {"id": 390, "name": "Cooking oil"}, {"id": 385, "name": "Butter"}]'::jsonb, false, ''),
  ('Cream pasta', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 101, "name": "Pasta"}, {"id": 24, "name": "Chicken"}, {"id": 92, "name": "Mushrooms"}, {"id": 38, "name": "Cream"}]'::jsonb, false, ''),
  ('Tomato pasta', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 101, "name": "Pasta"}, {"id": 24, "name": "Chicken"}, {"id": 148, "name": "Tomato"}, {"id": 96, "name": "Onion"}, {"id": 150, "name": "Tomato ketchup"}]'::jsonb, false, ''),
  ('Fish and chips', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 109, "name": "Potato"}, {"id": 47, "name": "Fish"}, {"id": 390, "name": "Cooking oil"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Chicken chop', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 109, "name": "Potato"}, {"id": 157, "name": "White rice"}, {"id": 24, "name": "Chicken"}, {"id": 81, "name": "Lettuce"}]'::jsonb, true, 'Deep-fried — the oil makes this unsuitable for prep no matter what goes into it.'),
  ('Chicken noodle soup', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 165, "name": "Yellow noodles"}, {"id": 24, "name": "Chicken"}, {"id": 19, "name": "Carrot"}, {"id": 28, "name": "Clear chicken broth"}]'::jsonb, false, ''),
  ('Plain rice noodles', ARRAY['lunch', 'dinner']::dish_meal_type[], 'DIETICIAN', '[{"id": 8, "name": "Bee hoon"}]'::jsonb, false, ''),

    -- --- TTSH tier (58 dishes) ---
  ('White rice', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 380, "name": "White rice"}]'::jsonb, false, ''),
  ('White porridge', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 379, "name": "White porridge"}]'::jsonb, false, ''),
  ('Bee hoon', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 306, "name": "Bee hoon"}]'::jsonb, false, ''),
  ('Kway teow', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 344, "name": "Kway teow"}]'::jsonb, false, ''),
  ('Mee sua', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 350, "name": "Mee sua"}]'::jsonb, false, ''),
  ('White bread', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 378, "name": "White bread"}]'::jsonb, false, ''),
  ('Plain crackers', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 413, "name": "Plain crackers"}]'::jsonb, false, ''),
  ('Plain biscuits', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 412, "name": "Plain biscuits"}]'::jsonb, false, ''),
  ('Rice cereal', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 418, "name": "Rice cereal"}]'::jsonb, false, ''),
  ('Yellow noodles', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 165, "name": "Yellow noodles"}]'::jsonb, false, ''),
  ('Mee pok', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 86, "name": "Mee pok"}]'::jsonb, false, ''),
  ('Mee kia', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 85, "name": "Mee kia"}]'::jsonb, false, ''),
  ('Pasta', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 101, "name": "Pasta"}]'::jsonb, false, ''),
  ('Brown rice', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 312, "name": "Brown rice"}]'::jsonb, true, 'High in fibre, which leaves residue and can hide the bowel lining.'),
  ('Brown rice porridge', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 313, "name": "Brown rice porridge"}]'::jsonb, true, 'High in fibre, which leaves residue and can hide the bowel lining.'),
  ('Wholemeal bread', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 382, "name": "Wholemeal bread"}]'::jsonb, true, 'High in fibre, which leaves residue and can hide the bowel lining.'),
  ('Wholegrain bread', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 381, "name": "Wholegrain bread"}]'::jsonb, true, 'High in fibre, which leaves residue and can hide the bowel lining.'),
  ('Chapati', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 317, "name": "Chapati"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Oats', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 353, "name": "Oats"}]'::jsonb, true, 'High in fibre, which leaves residue and can hide the bowel lining.'),
  ('Barley', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 303, "name": "Barley"}]'::jsonb, true, 'High in fibre, which leaves residue and can hide the bowel lining.'),
  ('Muesli', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 351, "name": "Muesli"}]'::jsonb, true, 'High in fibre from grains and extras, which leave residue.'),
  ('Popcorn', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 361, "name": "Popcorn"}]'::jsonb, true, 'Hulls and fibre leave residue that is hard to clear.'),
  ('Bran cereal', ARRAY['breakfast', 'snack']::dish_meal_type[], 'TTSH', '[{"id": 310, "name": "Bran cereal"}]'::jsonb, true, 'Very high in fibre, which leaves a lot of residue.'),
  ('Plain prata', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 416, "name": "Plain prata"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Plain naan', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 414, "name": "Plain naan"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Plain pancake', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 415, "name": "Plain pancake"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Plain waffle', ARRAY['breakfast']::dish_meal_type[], 'TTSH', '[{"id": 417, "name": "Plain waffle"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Chicken', ARRAY['lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 318, "name": "Chicken"}]'::jsonb, false, ''),
  ('Fish', ARRAY['lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 331, "name": "Fish"}]'::jsonb, false, ''),
  ('Prawns', ARRAY['lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 110, "name": "Prawns"}]'::jsonb, false, ''),
  ('Squid', ARRAY['lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 136, "name": "Squid"}]'::jsonb, false, ''),
  ('Egg', ARRAY['lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 329, "name": "Egg"}]'::jsonb, false, ''),
  ('Shellfish', ARRAY['lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 124, "name": "Shellfish"}]'::jsonb, false, ''),
  ('Cooking oil', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 411, "name": "Cooking oil"}]'::jsonb, false, ''),
  ('Butter', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 409, "name": "Butter"}]'::jsonb, false, ''),
  ('Mayonnaise', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 84, "name": "Mayonnaise"}]'::jsonb, false, ''),
  ('Coconut milk', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 33, "name": "Coconut milk"}]'::jsonb, false, ''),
  ('Coconut flesh', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 410, "name": "Coconut flesh"}]'::jsonb, false, ''),
  ('Kaya', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'TTSH', '[{"id": 72, "name": "Kaya"}]'::jsonb, false, ''),
  ('Fresh milk', ARRAY['breakfast', 'drink']::dish_meal_type[], 'TTSH', '[{"id": 52, "name": "Fresh milk"}]'::jsonb, false, ''),
  ('Yoghurt', ARRAY['breakfast', 'drink']::dish_meal_type[], 'TTSH', '[{"id": 166, "name": "Yoghurt"}]'::jsonb, false, ''),
  ('Cheese', ARRAY['breakfast', 'drink']::dish_meal_type[], 'TTSH', '[{"id": 22, "name": "Cheese"}]'::jsonb, false, ''),
  ('Condensed milk', ARRAY['breakfast', 'drink']::dish_meal_type[], 'TTSH', '[{"id": 35, "name": "Condensed milk"}]'::jsonb, false, ''),
  ('Evaporated milk', ARRAY['breakfast', 'drink']::dish_meal_type[], 'TTSH', '[{"id": 46, "name": "Evaporated milk"}]'::jsonb, false, ''),
  ('Cream', ARRAY['breakfast', 'drink']::dish_meal_type[], 'TTSH', '[{"id": 38, "name": "Cream"}]'::jsonb, false, ''),
  ('Soy milk', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 131, "name": "Soy milk"}]'::jsonb, false, ''),
  ('Kopi-O', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 343, "name": "Kopi-O"}]'::jsonb, false, ''),
  ('Teh-O', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 375, "name": "Teh-O"}]'::jsonb, false, ''),
  ('Black coffee', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 309, "name": "Black coffee"}]'::jsonb, false, ''),
  ('Plain tea', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 360, "name": "Plain tea"}]'::jsonb, false, ''),
  ('Kopi', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 341, "name": "Kopi"}]'::jsonb, false, ''),
  ('Teh', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 372, "name": "Teh"}]'::jsonb, false, ''),
  ('Kopi-C', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 342, "name": "Kopi-C"}]'::jsonb, false, ''),
  ('Teh-C', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 374, "name": "Teh-C"}]'::jsonb, false, ''),
  ('Teh tarik', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 373, "name": "Teh tarik"}]'::jsonb, false, ''),
  ('Barley water', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 304, "name": "Barley water"}]'::jsonb, true, 'Barley is a high-fibre grain and is grouped with foods to avoid.'),
  ('Bandung', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 408, "name": "Bandung"}]'::jsonb, false, ''),
  ('Soy bean drink', ARRAY['drink']::dish_meal_type[], 'TTSH', '[{"id": 130, "name": "Soy bean drink"}]'::jsonb, false, ''),

    -- --- SKH tier — mirrors the TTSH dish list, scored on SKH's own ingredient rows (58 dishes) ---
  ('White rice', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 291, "name": "White rice"}]'::jsonb, false, ''),
  ('White porridge', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 290, "name": "White porridge"}]'::jsonb, false, ''),
  ('Bee hoon', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 172, "name": "Bee hoon"}]'::jsonb, false, ''),
  ('Kway teow', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 224, "name": "Kway teow"}]'::jsonb, false, ''),
  ('Mee sua', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 233, "name": "Mee sua"}]'::jsonb, false, ''),
  ('White bread', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 289, "name": "White bread"}]'::jsonb, false, ''),
  ('Plain crackers', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 403, "name": "Plain crackers"}]'::jsonb, false, ''),
  ('Plain biscuits', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 250, "name": "Plain biscuits"}]'::jsonb, false, ''),
  ('Rice cereal', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 262, "name": "Rice cereal"}]'::jsonb, false, ''),
  ('Yellow noodles', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 298, "name": "Yellow noodles"}]'::jsonb, false, ''),
  ('Mee pok', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 232, "name": "Mee pok"}]'::jsonb, false, ''),
  ('Mee kia', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 231, "name": "Mee kia"}]'::jsonb, false, ''),
  ('Pasta', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 244, "name": "Pasta"}]'::jsonb, false, ''),
  ('Brown rice', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 178, "name": "Brown rice"}]'::jsonb, true, 'High in fibre, which leaves residue in the bowel.'),
  ('Brown rice porridge', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 179, "name": "Brown rice porridge"}]'::jsonb, true, 'High in fibre, which leaves residue in the bowel.'),
  ('Wholemeal bread', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 296, "name": "Wholemeal bread"}]'::jsonb, true, 'High in fibre, which leaves residue in the bowel.'),
  ('Wholegrain bread', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 293, "name": "Wholegrain bread"}]'::jsonb, true, 'High in fibre, which leaves residue in the bowel.'),
  ('Chapati', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 183, "name": "Chapati"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Oats', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 239, "name": "Oats"}]'::jsonb, true, 'High in fibre, which leaves residue in the bowel.'),
  ('Barley', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 5, "name": "Barley"}]'::jsonb, true, 'High in fibre, which leaves residue and can hide the bowel lining.'),
  ('Muesli', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 90, "name": "Muesli"}]'::jsonb, true, 'High in fibre from grains, fruit and seeds, which leave residue.'),
  ('Popcorn', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 108, "name": "Popcorn"}]'::jsonb, true, 'Hulls and fibre leave residue that is hard to clear.'),
  ('Bran cereal', ARRAY['breakfast', 'snack']::dish_meal_type[], 'SKH', '[{"id": 13, "name": "Bran cereal"}]'::jsonb, true, 'Very high in fibre, which leaves a lot of residue.'),
  ('Plain prata', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 406, "name": "Plain prata"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Plain naan', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 404, "name": "Plain naan"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Plain pancake', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 405, "name": "Plain pancake"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Plain waffle', ARRAY['breakfast']::dish_meal_type[], 'SKH', '[{"id": 407, "name": "Plain waffle"}]'::jsonb, true, 'Cooked in oil or ghee on the griddle — too rich for prep even when plain.'),
  ('Chicken', ARRAY['lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 186, "name": "Chicken"}]'::jsonb, false, ''),
  ('Fish', ARRAY['lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 203, "name": "Fish"}]'::jsonb, false, ''),
  ('Prawns', ARRAY['lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 254, "name": "Prawns"}]'::jsonb, false, ''),
  ('Squid', ARRAY['lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 273, "name": "Squid"}]'::jsonb, false, ''),
  ('Egg', ARRAY['lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 201, "name": "Egg"}]'::jsonb, false, ''),
  ('Shellfish', ARRAY['lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 266, "name": "Shellfish"}]'::jsonb, false, ''),
  ('Cooking oil', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 402, "name": "Cooking oil"}]'::jsonb, false, ''),
  ('Butter', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 400, "name": "Butter"}]'::jsonb, false, ''),
  ('Mayonnaise', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 84, "name": "Mayonnaise"}]'::jsonb, false, ''),
  ('Coconut milk', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 33, "name": "Coconut milk"}]'::jsonb, false, ''),
  ('Coconut flesh', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 401, "name": "Coconut flesh"}]'::jsonb, false, ''),
  ('Kaya', ARRAY['breakfast', 'lunch', 'dinner']::dish_meal_type[], 'SKH', '[{"id": 72, "name": "Kaya"}]'::jsonb, false, ''),
  ('Fresh milk', ARRAY['breakfast', 'drink']::dish_meal_type[], 'SKH', '[{"id": 206, "name": "Fresh milk"}]'::jsonb, true, 'Milk is avoided because it is not part of the allowed fluid list.'),
  ('Yoghurt', ARRAY['breakfast', 'drink']::dish_meal_type[], 'SKH', '[{"id": 299, "name": "Yoghurt"}]'::jsonb, true, 'Yoghurt is avoided on this hospital’s low-residue list.'),
  ('Cheese', ARRAY['breakfast', 'drink']::dish_meal_type[], 'SKH', '[{"id": 184, "name": "Cheese"}]'::jsonb, true, 'Cheese is avoided on this hospital’s low-residue list.'),
  ('Condensed milk', ARRAY['breakfast', 'drink']::dish_meal_type[], 'SKH', '[{"id": 35, "name": "Condensed milk"}]'::jsonb, false, ''),
  ('Evaporated milk', ARRAY['breakfast', 'drink']::dish_meal_type[], 'SKH', '[{"id": 46, "name": "Evaporated milk"}]'::jsonb, false, ''),
  ('Cream', ARRAY['breakfast', 'drink']::dish_meal_type[], 'SKH', '[{"id": 38, "name": "Cream"}]'::jsonb, false, ''),
  ('Soy milk', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 269, "name": "Soy milk"}]'::jsonb, true, 'Soy milk is avoided on this hospital’s fluid list.'),
  ('Kopi-O', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 223, "name": "Kopi-O"}]'::jsonb, true, 'Dark coffee/tea is avoided because it can affect the bowel view.'),
  ('Teh-O', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 281, "name": "Teh-O"}]'::jsonb, true, 'Dark coffee/tea is avoided because it can affect the bowel view.'),
  ('Black coffee', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 176, "name": "Black coffee"}]'::jsonb, true, 'Dark coffee/tea is avoided because it can affect the bowel view.'),
  ('Plain tea', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 251, "name": "Plain tea"}]'::jsonb, true, 'Dark coffee/tea is avoided because it can affect the bowel view.'),
  ('Kopi', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 221, "name": "Kopi"}]'::jsonb, true, 'Coffee/tea is avoided; milk drinks are also not allowed.'),
  ('Teh', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 278, "name": "Teh"}]'::jsonb, true, 'Coffee/tea is avoided; milk drinks are also not allowed.'),
  ('Kopi-C', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 222, "name": "Kopi-C"}]'::jsonb, true, 'Coffee/tea is avoided; milk drinks are also not allowed.'),
  ('Teh-C', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 280, "name": "Teh-C"}]'::jsonb, true, 'Coffee/tea is avoided; milk drinks are also not allowed.'),
  ('Teh tarik', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 279, "name": "Teh tarik"}]'::jsonb, true, 'Coffee/tea is avoided; milk drinks are also not allowed.'),
  ('Barley water', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 6, "name": "Barley water"}]'::jsonb, false, ''),
  ('Bandung', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 399, "name": "Bandung"}]'::jsonb, false, ''),
  ('Soy bean drink', ARRAY['drink']::dish_meal_type[], 'SKH', '[{"id": 268, "name": "Soy bean drink"}]'::jsonb, false, '');

